version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: vsi-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage:Z
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - vsi-network

  vsi-service:
    build: .
    container_name: vsi-service
    ports:
      - "3000:3000"
    volumes:
      # Mount uploads directory to host for file persistence and access
      - ./uploads:/app/uploads:Z
      # Mount user data directory to host for persistence
      - ./data/users:/app/data:Z
    environment:
      - NODE_ENV=production
      - PORT=3000
      - QDRANT_URL=http://qdrant:6333
      - JWT_SECRET=${JWT_SECRET:-your-default-jwt-secret-change-this}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - API_KEY=${API_KEY:-}
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-info}
      - ALLOW_SELF_REGISTRATION=${ALLOW_SELF_REGISTRATION:-false}
      - ALLOW_RAPIDAPI_USERS=${ALLOW_RAPIDAPI_USERS:-false}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/auth/debug/users"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - vsi-network

networks:
  vsi-network:
    driver: bridge

volumes:
  qdrant-data:
    driver: local
  vsi-uploads:
    driver: local
  vsi-userdata:
    driver: local
