version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vsi-postgres
    environment:
      POSTGRES_DB: vsi_db
      POSTGRES_USER: vsi_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vsi_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-READY", "pg_isready", "-U", "vsi_user", "-d", "vsi_db"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - vsi-network

  redis:
    image: redis:7-alpine
    container_name: vsi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - vsi-network

  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: vsi-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage:Z
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - vsi-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  vsi-service:
    build: .
    container_name: vsi-service
    ports:
      - "3000:3000"
    volumes:
      # Mount uploads directory to host for file persistence and access
      - vsi-uploads:/app/uploads:Z
      # Mount user data directory to host for persistence
      - vsi-userdata:/app/data:Z
    environment:
      - NODE_ENV=production
      - PORT=3000
      - QDRANT_URL=http://qdrant:6333
      - JWT_SECRET=${JWT_SECRET:-your-default-jwt-secret-change-this}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - API_KEY=${API_KEY:-}
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-info}
      - ALLOW_SELF_REGISTRATION=${ALLOW_SELF_REGISTRATION:-false}
      - ALLOW_RAPIDAPI_USERS=${ALLOW_RAPIDAPI_USERS:-false}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - DATABASE_URL=postgresql://vsi_user:${POSTGRES_PASSWORD:-vsi_password}@postgres:5432/vsi_db
      - REDIS_URL=redis://redis:6379
      - ENABLE_USAGE_TRACKING=true
      - ENABLE_TIER_LIMITS=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/auth/debug/users"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - vsi-network

networks:
  vsi-network:
    driver: bridge

volumes:
  qdrant-data:
    driver: local
  vsi-uploads:
    driver: local
  vsi-userdata:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
